### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by benjsmi** [dangrossman/Bookmarkly#8]
Just checking to see if @dangrossman is still maintaining this project.

**Comment by dangrossman** [comment]
This was never meant to be a maintained project; it was a code dump to go with a tutorial in 2012. I haven't made any changes since 2012, and there's been no interest in any updates since then either. This is the first issue in 3 years.

There's a pull request that updates the code and dependencies for more modern node.js from earlier this month. I haven't had a chance to test it yet. I'm sure it'd conflict with what you just submitted.

**Comment by luchenqun** [comment]
http://mybookmark.cn
